/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ratownik;

import java.awt.Graphics;

/**
 *
 * @author Tomzdon
 */
public class Rameczka extends javax.swing.JFrame {
     
    public int t_x;
    public int t_y;
    public int r_x;
    public int r_y;
    public int Vpp;
    public int Vmm;
     public int tx;
     public int ty;
   //public test rys ;
   public Rysowanie rys;
   public double[] czass;
   private double[] s1=new double[401];
   private double[] s2=new double[401];
   private double[] t1=new double[401];
   private double[] t2=new double[401];
   private double[] t=new double[401];
  private int wartosc;
  private double lower=0;
  public Rameczka tom;
    
    public Rameczka() {
        initComponents();
    
            rys=new Rysowanie(t_x,t_y,r_x,r_y);
            rys.setSize(400,200);
            jPanel1.add(rys);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aktualuzuj = new javax.swing.JButton();
        tonacyX = new javax.swing.JTextField();
        tonacyY = new javax.swing.JTextField();
        ratownikX = new javax.swing.JTextField();
        ratownikY = new javax.swing.JTextField();
        predkoscMorze = new javax.swing.JTextField();
        predkoscPlaza = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jLabel1.setText("Tonący");

        jLabel4.setText("Ratownik");

        jLabel7.setText("Prędkość");

        aktualuzuj.setText("Aktualizuj");
        aktualuzuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktualuzujActionPerformed(evt);
            }
        });

        tonacyX.setText("Tx");

        tonacyY.setText("Ty");

        ratownikX.setText("Rx");

        ratownikY.setText("Ry");

        predkoscMorze.setText("Vm");

        predkoscPlaza.setText("Vp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tonacyY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addComponent(tonacyX, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ratownikX)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ratownikY))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(predkoscMorze, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(predkoscPlaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(aktualuzuj)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tonacyX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratownikX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(predkoscMorze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tonacyY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratownikY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(predkoscPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aktualuzuj)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aktualuzujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktualuzujActionPerformed
        if(evt.getSource()==aktualuzuj){
          
     t_x=   gettX();
     t_y=   gettY();
     r_x=   getrX();
     r_y=   getrY();
     Vpp=   getVp();
     Vmm=   getVm();
      tom=new Rameczka();
     wartosc=   tom.optymal(t_x,t_y,r_x,r_y,Vpp,Vmm);
      
     
        
            System.out.println(t_x+" "+t_y);
      
     
    rys.ratownik_x=r_x;
    rys.ratownik_y=r_y;
    rys.tonocy_x=tx;
    rys.tonocy_y=100-ty;
    rys.X=wartosc;
    rys.Y=100;
    rys.repaint();
 
            System.out.println(wartosc);
    
    
    
       
          
        }
       
    }//GEN-LAST:event_aktualuzujActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
      
         tx=  evt.getX();
       ty=evt.getY();
        System.out.println(tx+ "  " + ty);
        
    }//GEN-LAST:event_jPanel1MouseClicked
   
      public int gettX(){
                String tonacy_x=tonacyX.getText();
           int t_x1=Integer.parseInt(tonacy_x);
          t_x=t_x1;
          return t_x;
      }
          public int gettY(){
             String tonacy_y=tonacyY.getText();
            t_y=Integer.parseInt(tonacy_y);
       
          return t_y;
      }
             public int getrX(){
               String ratownik=ratownikX.getText();
            r_x=Integer.parseInt(ratownik);
          return r_x;
      }
                   public int getrY(){
                 String ratownik_y=ratownikY.getText();
            r_y=Integer.parseInt(ratownik_y);
          return r_y;
                   }
      public int getVm(){
             String Vp=predkoscMorze.getText();
            Vmm=Integer.parseInt(Vp);
          return Vmm;
      }
      public int getVp(){
            String Vm=predkoscPlaza.getText();
            Vpp=Integer.parseInt(Vm);
          return Vpp;
      }
      
      public int optymal(int x_t,int y_t,int x_r,int y_r,int Vppp,int Vmmm){
          for(int i=0; i<401;i++){
              int x=i;
              int y=200;
              //r_y=r_y-200;
               s1[i]=Math.sqrt(Math.pow((x-x_r),2)+Math.pow((y_r-y),2));
              
             
               s2[i]=Math.sqrt(Math.pow((x-x_t),2)+Math.pow((y_t),2));
              
               t1[i]=s1[i]/Vppp;
               t2[i]=s2[i]/Vmmm;
               t[i]=t1[i]+t2[i];
             // czass[i]=t;
       
                 
              
          }
          //for(int j =0;j <401;j++){
            //  System.out.println(czass[j]);
          //}
           for(int k=0;k<401;k++){
           
              if(lower==0){
                  lower=t[k];
                  
              }
              if(t[k]<lower){
              lower=t[k];
              wartosc=k;
              
          }
          }   
          return wartosc;
      }
     
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rameczka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rameczka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rameczka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rameczka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rameczka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aktualuzuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField predkoscMorze;
    private javax.swing.JTextField predkoscPlaza;
    private javax.swing.JTextField ratownikX;
    private javax.swing.JTextField ratownikY;
    private javax.swing.JTextField tonacyX;
    private javax.swing.JTextField tonacyY;
    // End of variables declaration//GEN-END:variables
}
